name: Deploy Django API na EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Conectar na EC2 e atualizar app
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/projeto-django-api
          git pull origin main
          sudo docker compose down
          sudo docker compose build
          sudo docker compose up -d
